[masters]
k8s-master-0 ansible_host=10.4.0.10 keepalived_state=MASTER keepalived_priority=150
k8s-master-1 ansible_host=10.4.0.11 keepalived_state=BACKUP keepalived_priority=140
k8s-master-2 ansible_host=10.4.0.12 keepalived_state=BACKUP keepalived_priority=130

[workers]
k8s-worker-0 ansible_host=10.4.0.20
k8s-worker-1 ansible_host=10.4.0.21
k8s-worker-2 ansible_host=10.4.0.22

[k8s_cluster:children]
masters
workers

[control_plane_init]
k8s-master-0

[control_plane_join]
k8s-master-1
k8s-master-2
