apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-app-tls
  namespace: demo-app
spec:
  secretName: demo-app-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - demo-app.k8s-homelab.jacobbanghart.com
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
