apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - grafana.k8s-homelab.jacobbanghart.com
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
